name: Update Issue Title

on:
  issues:
    types: [opened, labeled]

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update issue title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER | jq -r '.labels[].name')
          NEW_TITLE="[docs]: ${{ github.event.issue.title }}"
          for LABEL in $LABELS; do
            if [[ "$LABEL" == "view" ]]; then
              NEW_TITLE="[view]: ${{ github.event.issue.title }}"
            elif [[ "$LABEL" == "🔍 analysis engine" ]]; then
              NEW_TITLE="[engine]: ${{ github.event.issue.title }}"
            fi
          done
          curl -s -H "Authorization: token $GITHUB_TOKEN" -X PATCH -d "{\"title\":\"$NEW_TITLE\"}" https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER